=== denskyline333/JS-labs/xml2/xml2.dtd
<!DOCTYPE faculty [
<!ELEMENT faculty (specialization)>
<!ELEMENT specialization (name,TIME,PAGES,PASSING)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT TIME (#PCDATA)>
<!ELEMENT PAGES (#PCDATA)>
<!ELEMENT PASSING (#PCDATA)>
]>

=== denskyline333/JS-labs/xml2/xml2.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/css" href="css1.css"?>

<!DOCTYPE faculty SYSTEM "xml2.dtd">

<faculty>
    <specialization>
        <name>БГТУ</name>
        <TIME>220</TIME>
        <PAGES>88</PAGES>
        <PASSING>Минск</PASSING>
    </specialization>
    <specialization>
        <name>БГУИР</name>
        <TIME>235</TIME>
        <PAGES>78</PAGES>
        <PASSING>Минск</PASSING>
    </specialization>
    <specialization>
        <name>БНТУ</name>
        <TIME>228</TIME>
        <PAGES>60</PAGES>
        <PASSING>Минск</PASSING>
    </specialization>
</faculty>
